---

- name: Install DNS Servers
  hosts: ns_servers
  tasks:
    - name: Testing role
      include_role:
        name: ansible-role-bind9
    - name: install master zones
      copy:
        src: example.org.zone
        dest: /etc/named/masters/
        owner: root
        group: "{{ dns_usergroup }}"
        mode: 0640
      notify: restart DNS system
      when: inventory_hostname == 'ansible-test-ns1'