---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ansible-test-ns1
    groups:
      - ns_servers
    source:
      alias: 'centos/7/amd64'
    image: 'centos:7.6.1810'
  - name: ansible-test-ns2
    groups:
      - ns_servers
    source:
      alias: 'centos/7/amd64'
    image: 'centos:7.6.1810'
  - name: ansible-test-outside
    source:
      alias: 'centos/7/amd64'
    image: 'centos:7.6.1810'
lint: |
  set -e
  yamllint .
  
#ansible-lint
#flake8
provisioner:
  name: ansible
  options:
    vvv: True
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: junit, profile_tasks, timer, yaml
    ssh_connection:
      pipelining: false
verifier:
  name: ansible
