---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ansible-test-ns1
    groups:
      - ns_servers
    source:
      alias: 'ubuntu/2004/amd64'
    image: 'registry.gitlab.com/cherubits/automation/images/docker-ubuntu2004-ansible:latest'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: false
  - name: ansible-test-ns2
    groups:
      - ns_servers
    source:
      alias: 'ubuntu/2004/amd64'
    image: 'registry.gitlab.com/cherubits/automation/images/docker-ubuntu2004-ansible:latest'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: false
  - name: ansible-test-outside
    source:
      alias: 'ubuntu/2004/amd64'
    image: 'registry.gitlab.com/cherubits/automation/images/docker-ubuntu2004-ansible:latest'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: false
lint: |
  set -e
  yamllint .
  
#ansible-lint
#flake8
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_user: root
      become_user: root
      no_log: false
      callback_whitelist: junit, profile_tasks, timer, yaml
      interpreter_python: auto_silent
    #  roles_path: "../../../"
    ssh_connection:
      pipelining: false
verifier:
  name: ansible
